data:
  base_dir: "/Volumes/ugly/PANOPTIC_DATA"

  # INPUT
  cptac_dicom_dir: "/Volumes/ugly/PANOPTIC_DATA/CPTAC-PDA"
  rnaseq_cct_dir: "/Volumes/ugly/PANOPTIC_DATA/cptac_rnaseq/RNAseq_Tumor.cct"

  # OUTPUTS
  cptac_nifti_dir: "/Volumes/ugly/PANOPTIC_DATA/cptac_nifti"
  artifacts_dir: "/Users/asiyah/Documents/PANOPCTIC_v1/pdac/artifacts"

  imaging_index_csv: "imaging_index.csv"
  imaging_qc_log_csv: "imaging_qc_log.csv"
  imaging_embeddings_csv: "imaging_embeddings.csv"
  imaging_embeddings_pt: "imaging_embeddings.pt"

  molecular_index_csv: "molecular_index.csv"
  molecular_labels_csv: "molecular_labels.csv"
  molecular_embeddings_csv: "molecular_embeddings.csv"
  molecular_embeddings_pt: "molecular_embeddings.pt"

  molecular_gnn_pt: "molecular_gnn.pt"
  molecular_gnn_index_csv: "molecular_gnn_index.csv"
  
  models_dir: "models"

preprocess:
  hu_min: -150
  hu_max: 250
  k_slices: 8
  slice_pool: 24
  patch_resize: 256
  patch_crop: 224

embeddings:
  batch_size: 4
  num_workers: 0

molecular:
  embedding_dim: 256
  hidden_dim: 1024