data:
  base_dir: "/Volumes/ugly/PANOPTIC_DATA"

  # INPUT
  cptac_dicom_dir: "/Volumes/ugly/PANOPTIC_DATA/CPTAC-PDA"

  # OUTPUTS
  cptac_nifti_dir: "/Volumes/ugly/PANOPTIC_DATA/cptac_nifti"
  artifacts_dir: "/Users/asiyah/Documents/PANOPCTIC_v1/pdac/artifacts"

  imaging_index_csv: "imaging_index.csv"
  imaging_qc_log_csv: "imaging_qc_log.csv"
  imaging_embeddings_csv: "imaging_embeddings.csv"
  imaging_embeddings_pt: "imaging_embeddings.pt"

preprocess:
  hu_min: -150
  hu_max: 250
  k_slices: 8
  slice_pool: 24
  patch_resize: 256
  patch_crop: 224

embeddings:
  batch_size: 4
  num_workers: 0
